// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/demo" | "/advert-features-preview" | "/advert-preview" | "/app" | "/auth/error" | "/billing" | "/brand" | "/complete-signup" | "/debug/subscription" | "/faq" | "/features" | "/forgot-password" | "/how-it-works" | "/login" | "/maintenance" | "/pricing" | "/privacy-policy" | "/reset-password" | "/signup" | "/signup/success" | "/store" | "/store/[slug]" | "/subscription-success" | "/subscription/success" | "/terms" | "/trial" | "/upgrade" | "/who-its-for"
type AppRouteHandlerRoutes = "/api/account/delete" | "/api/check-email" | "/api/contact" | "/api/create-checkout-session" | "/api/create-profile" | "/api/debug/env-check" | "/api/debug/subscription" | "/api/debug/subscription-sync" | "/api/demo" | "/api/demo/admin" | "/api/ensure-profile" | "/api/entitlement" | "/api/playlists/delete" | "/api/playlists/update" | "/api/r2" | "/api/store/audio" | "/api/store/checkout" | "/api/verify-checkout" | "/api/webhooks/stripe" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin/demo" | "/app" | "/billing" | "/complete-signup" | "/forgot-password" | "/login" | "/reset-password" | "/signup" | "/store" | "/subscription-success" | "/subscription/success" | "/trial" | "/upgrade"
type RedirectRoutes = "/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/admin/demo": {}
  "/advert-features-preview": {}
  "/advert-preview": {}
  "/api/account/delete": {}
  "/api/check-email": {}
  "/api/contact": {}
  "/api/create-checkout-session": {}
  "/api/create-profile": {}
  "/api/debug/env-check": {}
  "/api/debug/subscription": {}
  "/api/debug/subscription-sync": {}
  "/api/demo": {}
  "/api/demo/admin": {}
  "/api/ensure-profile": {}
  "/api/entitlement": {}
  "/api/playlists/delete": {}
  "/api/playlists/update": {}
  "/api/r2": {}
  "/api/store/audio": {}
  "/api/store/checkout": {}
  "/api/verify-checkout": {}
  "/api/webhooks/stripe": {}
  "/app": {}
  "/auth/callback": {}
  "/auth/error": {}
  "/billing": {}
  "/brand": {}
  "/complete-signup": {}
  "/debug/subscription": {}
  "/faq": {}
  "/features": {}
  "/forgot-password": {}
  "/how-it-works": {}
  "/login": {}
  "/maintenance": {}
  "/pricing": {}
  "/privacy-policy": {}
  "/reset-password": {}
  "/signup": {}
  "/signup/success": {}
  "/store": {}
  "/store/[slug]": { "slug": string; }
  "/subscription-success": {}
  "/subscription/success": {}
  "/terms": {}
  "/trial": {}
  "/upgrade": {}
  "/who-its-for": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin/demo": never
  "/app": never
  "/billing": never
  "/complete-signup": never
  "/forgot-password": never
  "/login": never
  "/reset-password": never
  "/signup": never
  "/store": never
  "/subscription-success": never
  "/subscription/success": never
  "/trial": never
  "/upgrade": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
