// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/demo">> = Specific
  const handler = {} as typeof import("../../app/admin/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advert-features-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advert-features-preview">> = Specific
  const handler = {} as typeof import("../../app/advert-features-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advert-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advert-preview">> = Specific
  const handler = {} as typeof import("../../app/advert-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/error">> = Specific
  const handler = {} as typeof import("../../app/auth/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand">> = Specific
  const handler = {} as typeof import("../../app/brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/complete-signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complete-signup">> = Specific
  const handler = {} as typeof import("../../app/complete-signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/subscription">> = Specific
  const handler = {} as typeof import("../../app/debug/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/success">> = Specific
  const handler = {} as typeof import("../../app/signup/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/store/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/[slug]">> = Specific
  const handler = {} as typeof import("../../app/store/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store">> = Specific
  const handler = {} as typeof import("../../app/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscription-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription-success">> = Specific
  const handler = {} as typeof import("../../app/subscription-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscription/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription/success">> = Specific
  const handler = {} as typeof import("../../app/subscription/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trial">> = Specific
  const handler = {} as typeof import("../../app/trial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/upgrade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upgrade">> = Specific
  const handler = {} as typeof import("../../app/upgrade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/who-its-for/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/who-its-for">> = Specific
  const handler = {} as typeof import("../../app/who-its-for/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/account/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/delete">> = Specific
  const handler = {} as typeof import("../../app/api/account/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/check-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-email">> = Specific
  const handler = {} as typeof import("../../app/api/check-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create-checkout-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-checkout-session">> = Specific
  const handler = {} as typeof import("../../app/api/create-checkout-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-profile">> = Specific
  const handler = {} as typeof import("../../app/api/create-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/env-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/env-check">> = Specific
  const handler = {} as typeof import("../../app/api/debug/env-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/subscription-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/subscription-sync">> = Specific
  const handler = {} as typeof import("../../app/api/debug/subscription-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/subscription">> = Specific
  const handler = {} as typeof import("../../app/api/debug/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/demo/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo/admin">> = Specific
  const handler = {} as typeof import("../../app/api/demo/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/demo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo">> = Specific
  const handler = {} as typeof import("../../app/api/demo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ensure-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ensure-profile">> = Specific
  const handler = {} as typeof import("../../app/api/ensure-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/entitlement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entitlement">> = Specific
  const handler = {} as typeof import("../../app/api/entitlement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/playlists/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/playlists/delete">> = Specific
  const handler = {} as typeof import("../../app/api/playlists/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/playlists/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/playlists/update">> = Specific
  const handler = {} as typeof import("../../app/api/playlists/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/r2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/r2">> = Specific
  const handler = {} as typeof import("../../app/api/r2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/store/audio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/audio">> = Specific
  const handler = {} as typeof import("../../app/api/store/audio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/store/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/store/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verify-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify-checkout">> = Specific
  const handler = {} as typeof import("../../app/api/verify-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/demo/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/demo">> = Specific
  const handler = {} as typeof import("../../app/admin/demo/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/complete-signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/complete-signup">> = Specific
  const handler = {} as typeof import("../../app/complete-signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forgot-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/forgot-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/store/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/store">> = Specific
  const handler = {} as typeof import("../../app/store/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscription-success/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/subscription-success">> = Specific
  const handler = {} as typeof import("../../app/subscription-success/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscription/success/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/subscription/success">> = Specific
  const handler = {} as typeof import("../../app/subscription/success/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trial/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/trial">> = Specific
  const handler = {} as typeof import("../../app/trial/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/upgrade/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/upgrade">> = Specific
  const handler = {} as typeof import("../../app/upgrade/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
