var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/account/delete/route.js")
R.c("server/chunks/[root-of-the-server]__002u7ka._.js")
R.c("server/chunks/[root-of-the-server]__07~uv_k._.js")
R.c("server/chunks/0kic_next_dist_esm_build_templates_app-route_0daj-7m.js")
R.c("server/chunks/11s5_@supabase_supabase-js_dist_index_mjs_0~zawi7._.js")
R.c("server/chunks/0323_stripe_esm_stripe_esm_node_0t-hjku.js")
R.c("server/chunks/node_modules__pnpm_0ft_rad._.js")
R.c("server/chunks/_next-internal_server_app_api_account_delete_route_actions_0s.a.t_.js")
R.m(88389)
module.exports=R.m(88389).exports
