var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/brand/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ebio1l._.js")
R.c("server/chunks/ssr/0kic_next_dist_esm_build_templates_app-page_10v004e.js")
R.c("server/chunks/ssr/_0lxj2.j._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ny2uoc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cpkprr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02za8dp._.js")
R.c("server/chunks/ssr/0kic_next_dist_0z9w4z.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0is4wz~._.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_0ci0p5g._.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_forbidden_0ab9dn-.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_unauthorized_0felnrc.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_global-error_0gw746f.js")
R.c("server/chunks/ssr/_next-internal_server_app_brand_page_actions_02v1_8p.js")
R.m(46079)
module.exports=R.m(46079).exports
