var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/signup/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x60wkc._.js")
R.c("server/chunks/ssr/0kic_next_dist_esm_build_templates_app-page_0h2_mpe.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ny2uoc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cpkprr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02za8dp._.js")
R.c("server/chunks/ssr/0kic_next_dist_0z9w4z.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0is4wz~._.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_0ci0p5g._.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_forbidden_0ab9dn-.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_unauthorized_0felnrc.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_global-error_0gw746f.js")
R.c("server/chunks/ssr/app_signup_layout_tsx_0uq7.7n._.js")
R.c("server/chunks/ssr/_next-internal_server_app_signup_page_actions_01t.ngc.js")
R.m(26859)
module.exports=R.m(26859).exports
