var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/who-its-for/page.js")
R.c("server/chunks/ssr/node_modules__pnpm_12qsq92._.js")
R.c("server/chunks/ssr/0kic_next_dist_esm_build_templates_app-page_0au7u_i.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ac0ezu._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ny2uoc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cpkprr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02za8dp._.js")
R.c("server/chunks/ssr/0kic_next_dist_0z9w4z.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0is4wz~._.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_0ci0p5g._.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_forbidden_0ab9dn-.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_unauthorized_0felnrc.js")
R.c("server/chunks/ssr/0kic_next_dist_client_components_builtin_global-error_0gw746f.js")
R.c("server/chunks/ssr/_next-internal_server_app_who-its-for_page_actions_12ir5ic.js")
R.m(1582)
module.exports=R.m(1582).exports
