#!/usr/bin/env node

/**
 * Build entry point used by `npm run build`.
 *
 * - Web build (default): just runs `next build`.
 * - Mobile build (NEXT_PUBLIC_BUILD_TARGET=mobile): temporarily removes the
 *   server-only routes that cannot exist in a static export (`output: export`),
 *   runs `next build` to produce the /out folder for Capacitor, then always
 *   restores the moved files — even if the build fails — so the working tree is
 *   never left in a broken state.
 *
 * This makes `NEXT_PUBLIC_BUILD_TARGET=mobile npm run build` work on its own,
 * matching the documented Capacitor workflow.
 */

const { execFileSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const isMobile = process.env.NEXT_PUBLIC_BUILD_TARGET === 'mobile'
const scriptsDir = __dirname
const projectRoot = process.cwd()
const backupDir = path.join(projectRoot, '.mobile-build-backup')

// Resolve the Next.js CLI directly instead of relying on PATH. Running the JS
// entry point through the current Node keeps App Router detection working even
// when `next` isn't on PATH in the caller's shell.
function resolveNextBin() {
  try {
    return require.resolve('next/dist/bin/next', { paths: [projectRoot] })
  } catch {
    return null
  }
}

function runNext(args) {
  const nextBin = resolveNextBin()
  if (nextBin) {
    execFileSync(process.execPath, [nextBin, ...args], { stdio: 'inherit', cwd: projectRoot })
  } else {
    // Fallback to PATH-resolved binary.
    execFileSync('next', args, { stdio: 'inherit', cwd: projectRoot })
  }
}

function runNode(scriptFile) {
  execFileSync(process.execPath, [path.join(scriptsDir, scriptFile)], {
    stdio: 'inherit',
    cwd: projectRoot,
  })
}

if (!isMobile) {
  // Standard web build.
  runNext(['build'])
  process.exit(0)
}

// Validate required public config before moving any files. Only variable
// names are printed, never their values.
const REQUIRED_MOBILE_ENV = [
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'NEXT_PUBLIC_API_BASE_URL',
]
const missingEnv = REQUIRED_MOBILE_ENV.filter((name) => !String(process.env[name] || '').trim())
if (missingEnv.length > 0) {
  console.error(
    `[build] Mobile build aborted. Missing required environment variable(s): ${missingEnv.join(', ')}`,
  )
  process.exit(1)
}
const apiBase = String(process.env.NEXT_PUBLIC_API_BASE_URL).trim()
if (!/^https:\/\//i.test(apiBase)) {
  console.error('[build] Mobile build aborted. NEXT_PUBLIC_API_BASE_URL must be an https:// URL.')
  process.exit(1)
}

// Self-heal: a previously interrupted mobile build (crash / Ctrl-C / OOM) can
// leave server-only routes stranded in `.mobile-build-backup`, so the working
// tree is half-moved. Building on top of that half-moved tree is what triggers
// the "Couldn't find a `pages` directory" error. Restore any stale backup first
// so every mobile build starts from a clean App Router tree.
if (fs.existsSync(backupDir)) {
  console.log('[build] Found leftover .mobile-build-backup — restoring before build...')
  runNode('restore-web-build.js')
}

// Route types generated by earlier web builds (tsconfig includes them) import
// server-only pages that the mobile prep moves out, which fails type checking.
// Set them aside for the mobile build and always put them back afterwards.
const staleTypesDir = path.join(projectRoot, '.mobile-build-stale-types')
const generatedTypeDirs = ['.next/types', '.next/dev/types', '.next-probe/types', '.next-probe/dev/types']

function restoreGeneratedTypes() {
  if (!fs.existsSync(staleTypesDir)) return
  for (const rel of generatedTypeDirs) {
    const parked = path.join(staleTypesDir, rel)
    if (!fs.existsSync(parked)) continue
    const target = path.join(projectRoot, rel)
    fs.rmSync(target, { recursive: true, force: true })
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.renameSync(parked, target)
    console.log(`Restored generated types: ${rel}`)
  }
  fs.rmSync(staleTypesDir, { recursive: true, force: true })
}

function parkGeneratedTypes() {
  for (const rel of generatedTypeDirs) {
    const source = path.join(projectRoot, rel)
    if (!fs.existsSync(source)) continue
    const parked = path.join(staleTypesDir, rel)
    fs.mkdirSync(path.dirname(parked), { recursive: true })
    fs.renameSync(source, parked)
  }
}

if (fs.existsSync(staleTypesDir)) {
  console.log('[build] Found leftover .mobile-build-stale-types — restoring before build...')
  restoreGeneratedTypes()
}

console.log('[build] Mobile target detected — preparing static export...')
runNode('prepare-mobile-build.js')

let buildError = null
try {
  parkGeneratedTypes()
  // Build the mobile static export with the default bundler. Do not pass extra
  // bundler flags here — this Next.js version rejects unknown build options.
  runNext(['build'])
} catch (err) {
  buildError = err
} finally {
  console.log('[build] Restoring web-only routes...')
  runNode('restore-web-build.js')
  restoreGeneratedTypes()
}

if (buildError) {
  console.error('[build] Mobile build failed.')
  process.exit(1)
}

console.log('[build] Mobile static export complete (see /out).')
