import { createServerClient } from '@supabase/ssr'
import { NextResponse, type NextRequest } from 'next/server'
import { evaluateForUser } from '@/lib/entitlement-server'

// Login is REQUIRED (but the app is free - there is no subscription/trial check).
// Logged-out users hitting a protected route are redirected to /login; logged-in
// users are allowed through. Set to true only to fully disable auth gating.
const BYPASS_AUTH = false

export async function updateSession(request: NextRequest) {
  // TEMPORARY bypass: skip all auth/subscription gating entirely
  if (BYPASS_AUTH) {
    return NextResponse.next()
  }

  // Local-dev bypass: skip auth entirely only during genuine `next dev`.
  //
  // We deliberately do NOT trust `NEXT_PUBLIC_V0_PREVIEW` here. That public flag
  // is set in this project's PRODUCTION environment (and is currently malformed),
  // so trusting it would bypass auth on the live site. Gating on NODE_ENV alone
  // means the deployed site ALWAYS enforces login regardless of that env value.
  if (process.env.NODE_ENV === "development") {
    return NextResponse.next()
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

  const { pathname } = request.nextUrl

  // Public routes that don't require authentication
  // NOTE: '/api/r2' is listed so the mobile app's cross-origin, token-authed
  // request is NOT redirected to /login (which would return HTML). The /api/r2
  // route enforces its own auth (cookie session OR Bearer access token), so
  // this does not weaken security — an unauthenticated call still gets 401.
  // NOTE: '/forgot-password' and '/reset-password' MUST be public. A user who
  // forgot their password is logged OUT, so if these were protected the middleware
  // would redirect them to /login before the page could load — which made the
  // "Forgot your password?" button look like it did nothing, and caused the reset
  // link from the email to bounce to /login and discard the recovery token.
  // NOTE: '/store' (the public music store, browse + preview) and '/api/store'
  // (its open preview / entitlement-gated audio endpoints) are public. The audio
  // API enforces its own entitlement check for clean masters, so listing it here
  // only exposes the already-public previews and returns 403 for gated downloads.
  // NOTE: '/robots.txt' and '/sitemap.xml' MUST be public. They are generated by
  // app/robots.ts and app/sitemap.ts and are fetched by crawlers with no session —
  // if the middleware redirected them to /login, search engines would index a login
  // page instead of the SEO files. They pass through the matcher (only image
  // extensions are excluded there), so they must be allowlisted here.
  const publicRoutes = ['/login', '/signup', '/forgot-password', '/reset-password', '/auth/callback', '/auth/confirm', '/auth/error', '/pricing', '/features', '/how-it-works', '/who-its-for', '/faq', '/terms', '/store', '/subscription-success', '/subscription/success', '/complete-signup', '/upgrade', '/privacy-policy', '/robots.txt', '/sitemap.xml', '/api/webhooks', '/api/create-checkout-session', '/api/create-profile', '/api/verify-checkout', '/api/check-email', '/api/debug', '/api/r2', '/api/store', '/debug']
  // The marketing homepage is public, but ONLY as an EXACT match. Using startsWith
  // for '/' would make every route public, so it's handled separately from the
  // prefix-matched list above. The player now lives at '/app' and stays protected
  // because it is NOT in publicRoutes.
  // The public interactive demo endpoint. It MUST be reachable by logged-out
  // visitors on the /features page, otherwise the middleware 307-redirects the
  // GET /api/demo fetch to /login and the demo never loads. An exact match on
  // '/api/demo' plus the '/api/demo/' prefix keeps this scoped to the demo API
  // only (it does NOT make other /api/* routes public). Routes beneath
  // /api/demo/ — e.g. the admin publish/disable endpoint — still enforce their
  // own auth internally (returning 401/403), so allowing them past the login
  // redirect here does not weaken security.
  const isDemoRoute = pathname === '/api/demo' || pathname.startsWith('/api/demo/')

  const isPublicRoute = pathname === '/' || isDemoRoute || publicRoutes.some(route => pathname.startsWith(route))

  // If Supabase is not configured, redirect protected routes to login
  if (!supabaseUrl || !supabaseAnonKey) {
    if (!isPublicRoute) {
      const url = request.nextUrl.clone()
      url.pathname = '/login'
      return NextResponse.redirect(url)
    }
    return NextResponse.next({ request })
  }

  let supabaseResponse = NextResponse.next({ request })

  const supabase = createServerClient(supabaseUrl, supabaseAnonKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll()
      },
      setAll(cookiesToSet) {
        cookiesToSet.forEach(({ name, value }) =>
          request.cookies.set(name, value)
        )
        supabaseResponse = NextResponse.next({ request })
        cookiesToSet.forEach(({ name, value, options }) =>
          supabaseResponse.cookies.set(name, value, options)
        )
      },
    },
  })

  // Refresh session if expired
  const {
    data: { user },
  } = await supabase.auth.getUser()

  // If user is not logged in and trying to access a protected route, send them
  // to /login and remember where they were headed via ?next= so we can return
  // them there after they sign in (e.g. /app -> /login?next=/app). Only the
  // internal path+query is preserved; safeNext on the login side rejects
  // anything that isn't a single-slash internal path, so this can't be abused
  // as an open redirect.
  if (!user && !isPublicRoute) {
    const url = request.nextUrl.clone()
    url.pathname = '/login'
    url.search = ''
    url.searchParams.set('next', pathname + request.nextUrl.search)
    return NextResponse.redirect(url)
  }

  // If user is logged in, keep them out of the LOGIN page (send to the player at
  // /app). Login alone grants access - there is no subscription/trial check.
  // Note: we intentionally do NOT redirect logged-in users away from '/', so they
  // can still view the public marketing homepage while signed in (the header shows
  // an "Open EQHO" link to /app in that case).
  //
  // '/signup' is deliberately EXCLUDED here: visiting /signup directly must ALWAYS
  // render the signup page, even for an authenticated user. Auto-redirecting an
  // existing session from /signup to /app was hiding the page entirely, so it is
  // no longer redirected.
  if (user) {
    if (pathname === '/login') {
      const url = request.nextUrl.clone()
      url.pathname = '/app'
      return NextResponse.redirect(url)
    }
  }

  // Entitlement gate for the player itself (`/app`). Reached only when we're in
  // production (dev/preview returned early above) and the user is logged in.
  // Before 1 Oct 2026 this always passes (free phase); after it, a user without
  // a valid entitlement is sent to /upgrade. /account, /billing and /upgrade are
  // NOT player routes, so a blocked user can still manage or start a subscription.
  if (user) {
    const isPlayerRoute = pathname === '/app' || pathname.startsWith('/app/')
    if (isPlayerRoute) {
      try {
        const { result } = await evaluateForUser(request, user)
        if (!result.allowed) {
          const url = request.nextUrl.clone()
          url.pathname = '/upgrade'
          url.search = ''
          return NextResponse.redirect(url)
        }
      } catch (err) {
        // Fail OPEN: never lock a paying/free user out because of a transient
        // profile-read error. The client gate re-checks on load as a backstop.
        console.error('[v0][middleware] entitlement check failed, allowing through:', err)
      }
    }
  }

  return supabaseResponse
}
