import { createServerClient } from '@supabase/ssr'
import { NextResponse, type NextRequest } from 'next/server'

// Login is REQUIRED (but the app is free - there is no subscription/trial check).
// Logged-out users hitting a protected route are redirected to /login; logged-in
// users are allowed through. Set to true only to fully disable auth gating.
const BYPASS_AUTH = false

export async function updateSession(request: NextRequest) {
  // TEMPORARY bypass: skip all auth/subscription gating entirely
  if (BYPASS_AUTH) {
    return NextResponse.next()
  }

  // V0 Preview bypass: skip auth entirely in development
  if (
    process.env.NODE_ENV === "development" ||
    process.env.NEXT_PUBLIC_V0_PREVIEW === "true"
  ) {
    return NextResponse.next()
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

  const { pathname } = request.nextUrl

  // Public routes that don't require authentication
  // NOTE: '/api/r2' is listed so the mobile app's cross-origin, token-authed
  // request is NOT redirected to /login (which would return HTML). The /api/r2
  // route enforces its own auth (cookie session OR Bearer access token), so
  // this does not weaken security — an unauthenticated call still gets 401.
  // NOTE: '/forgot-password' and '/reset-password' MUST be public. A user who
  // forgot their password is logged OUT, so if these were protected the middleware
  // would redirect them to /login before the page could load — which made the
  // "Forgot your password?" button look like it did nothing, and caused the reset
  // link from the email to bounce to /login and discard the recovery token.
  // NOTE: '/store' (the public music store, browse + preview) and '/api/store'
  // (its open preview / entitlement-gated audio endpoints) are public. The audio
  // API enforces its own entitlement check for clean masters, so listing it here
  // only exposes the already-public previews and returns 403 for gated downloads.
  // NOTE: '/robots.txt' and '/sitemap.xml' MUST be public. They are generated by
  // app/robots.ts and app/sitemap.ts and are fetched by crawlers with no session —
  // if the middleware redirected them to /login, search engines would index a login
  // page instead of the SEO files. They pass through the matcher (only image
  // extensions are excluded there), so they must be allowlisted here.
  const publicRoutes = ['/login', '/signup', '/forgot-password', '/reset-password', '/auth/callback', '/auth/confirm', '/auth/error', '/pricing', '/features', '/terms', '/store', '/subscription-success', '/subscription/success', '/complete-signup', '/upgrade', '/privacy-policy', '/robots.txt', '/sitemap.xml', '/api/webhooks', '/api/create-checkout-session', '/api/create-profile', '/api/verify-checkout', '/api/check-email', '/api/debug', '/api/r2', '/api/store', '/debug']
  // The marketing homepage is public, but ONLY as an EXACT match. Using startsWith
  // for '/' would make every route public, so it's handled separately from the
  // prefix-matched list above. The player now lives at '/app' and stays protected
  // because it is NOT in publicRoutes.
  const isPublicRoute = pathname === '/' || publicRoutes.some(route => pathname.startsWith(route))

  // If Supabase is not configured, redirect protected routes to login
  if (!supabaseUrl || !supabaseAnonKey) {
    if (!isPublicRoute) {
      const url = request.nextUrl.clone()
      url.pathname = '/login'
      return NextResponse.redirect(url)
    }
    return NextResponse.next({ request })
  }

  let supabaseResponse = NextResponse.next({ request })

  const supabase = createServerClient(supabaseUrl, supabaseAnonKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll()
      },
      setAll(cookiesToSet) {
        cookiesToSet.forEach(({ name, value }) =>
          request.cookies.set(name, value)
        )
        supabaseResponse = NextResponse.next({ request })
        cookiesToSet.forEach(({ name, value, options }) =>
          supabaseResponse.cookies.set(name, value, options)
        )
      },
    },
  })

  // Refresh session if expired
  const {
    data: { user },
  } = await supabase.auth.getUser()

  // If user is not logged in and trying to access a protected route
  if (!user && !isPublicRoute) {
    const url = request.nextUrl.clone()
    url.pathname = '/login'
    return NextResponse.redirect(url)
  }

  // If user is logged in, keep them out of the auth pages (send to the player at
  // /app). Login alone grants access - there is no subscription/trial check.
  // Note: we intentionally do NOT redirect logged-in users away from '/', so they
  // can still view the public marketing homepage while signed in (the header shows
  // an "Open EQHO" link to /app in that case).
  if (user) {
    if (pathname === '/login' || pathname === '/signup') {
      const url = request.nextUrl.clone()
      url.pathname = '/app'
      return NextResponse.redirect(url)
    }
  }

  return supabaseResponse
}
